name: Mirror to GitHub.com

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to public mirror
        run: |
          git remote add public https://${{ secrets.GITHUB_COM_TOKEN }}@github.com/chzzk-design/storybook.git
          git push public main --force
